### ISSUE TITLE
Better Instructions...

### ISSUE THREAD

**Issue by GDawg78** [dukelec/mbrush#27]
Guys,

I'm glad you're actively working on the firmware and software for the cube.

Any chance of better instructions on how to use the product though? Yes I can bash my way through using it, but the YouTube videos are getting a bit long in the tooth and the UI is a little confusing... 

Don't be discouraged though, I thank you and the team for your efforts! 

My request list is as follows:

**User Requests**

- [ ] New YouTube videos on how to use the product, more in depth

- [ ] iOS or Android Native Apps

- [ ] Full End user Manual

- [ ] How to properly clean, and care for the product

**Comment by frankcom** [comment]
It would be definitely interesting to improve the functionality with Native Apps. I think it is worth thinking of. All the best

**Comment by GDawg78** [comment]
Excellent, any chance of end user manuals or updating the YouTube Channel, I'm happy to help out if you'd like any help?
