### ISSUE TITLE
what causes "loading, please try later" error when i try to print?

### ISSUE THREAD

**Issue by weissup** [dukelec/mbrush#81]

**Comment by weissup** [comment]
in the developer console for chrome, i get these errors: 
![image](https://github.com/user-attachments/assets/bcd66336-6231-48f0-b2bf-59034bc6c495)

**Comment by weissup** [comment]
freshly reflashed it with the burner tool and latest firmware and now it is like this: 
![image](https://github.com/user-attachments/assets/433c7396-b420-4bec-a5e5-38aa5b8d2258)

**Comment by weissup** [comment]
i have gotten it to work again.  for anyone who is interested in wtf i did: 
1. delete site cookies for the page (click on Not Secure > Cookies / site data > manage on-device site data > then the tiny trash can) ... it will ask you to reload 
2. in developer console (F12 in chrome), set it to another browser (i set it to chrome - mac) 
3. reload and it SHOULD end with "MB init" which means the software has loaded successfully. 

![image](https://github.com/user-attachments/assets/2ee51a79-c3d7-48bb-851d-e256d144d834)

the software seems to ping the device every 200ms so if  the connection is not stable it will f up again. 
i would recommend always using it with dev console turned on just to see what the heck its doing. 
the device's wifi connection to my pc was very iffy, so i took off the front cover and exposed the circuitry
this allowed me to see the lights and how they were interacting based on my experience 
and also somewhat seemed to improve the wifi connection. 
it has remained connected to my pc for the past 28 minutes so far without dropping (it used to become an "unidentified network" after a few minutes)

**Comment by SpiritInAShell** [comment]
When sending print task to the printer:

I have experienced this error when using `Cromite` for Android. Switched to Chrome for Android and it worked.
